#ifndef __ERROR_CODES__
#define __ERROR_CODES__

#define INPUT_FILE_NOT_FOUND 1
#define INVALID_OUTPUT_DESTINATION 2
#define INVALID_ARGUMENTS_COUNT 3
#define UNKNOWN_VARIABLE 10
#define SYNTAX_ERROR 11
#define FUNCTION_UNBOUNDED_ERROR 20
#define NO_FEASIBLE_SOLUTION 21
#define SOLUTION_OUT_OF_BOUNDS 22
#define MEMORY_ERROR 90
#define INVALID_ARGUMENT 91
#define NO_INPUT_SPECIFIED 92
#define SANITY_CHECK_ERROR 93
#define PARSING_ERROR 94
#define RUNTIME_ERROR 95

#endif
